---
pagetitle: "Std Normal Area Between"
params:
  z1: -0.54
  z2: 1.24
---

```{r}
library("statplosion")
```

```{r}
z1<-params$z1; 
z2<-params$z2; 
```

```{r echo=FALSE}
area1_actual <- pnorm(z1)
area1_rounded <- round(area1_actual,4)
nearest_percent1 <- round(area1_rounded*100)

area2_actual <- pnorm(z2)
area2_rounded <- round(area2_actual,4)
nearest_percent2 <- round(area2_rounded*100)

area_between <- area2_rounded - area1_rounded
nearest_percent_between <- round(area_between*100)
```
Here is the picture of the area we want.  

```{r fig.height=2, fig.width=3.5, fig.align="center"}
std_normal_curve()
std_normal_shade_area_between(z1,z2)
std_normal_label_point(z1)
std_normal_label_point(z2)
```

We want the shaded region to the left of $z_2=`r z2`$ and to the right of $z_1 = `r z1`$

If we look up the areas in the standard normal z-table we find:

$$
\text{left tail area for } z_2 =`r area2_rounded` 
$$

$$
\text{left tail area for } z_1 =`r area1_rounded` 
$$
    
So the area between is:

$$
\text{area between} =`r area2_rounded` - `r area1_rounded` = `r area_between` 
$$

Rounded to the nearest percent this is `r nearest_percent_between`%. 

This means that the shaded area corresponds to `r nearest_percent_between`% of the entire data.
