library("knitr")
#library("rmarkdown")
#library("tictoc")
example_label<-function(s){}
# tic("running render")
# rmarkdown::render("NormalRightTail.Rmd","html_document")
# toc()
#tic("running knit")
opts_knit$set(upload.fun = image_uri)
opts_chunk$set(echo = FALSE)
env<-new.env()
env$params<-list(n=15)
knit("Scatterplot.Rmd", env=env)
#toc()
